### PR TITLE
Modify Rules Screen

### PR DESCRIPTION
**Pull request by ntvkhoasgt**
I modify rules screen. 
Please confirm

**Result:**
image
image

### CODE REVIEW

**Comment by hellosagar** [comment]
Thanks, @ntvkhoasgt for showing your interest. I will review it

**Comment by hellosagar** [comment]
@ntvkhoasgt Gif looks good, but when Im swiping the back button, and progress indicator is also moving with the swipe.
So, you should stick the `back button`, Title which is `Rule` and for progress, indicator takes a look here - [LINK](https://github.com/tommybuonomo/dotsindicator ). what you've implemented its kind of a hacky way.

The rest looks good. :)

**Comment by ntvkhoasgt** [comment]
> 
> 
> @ntvkhoasgt Gif looks good, but when Im swiping the back button, and progress indicator is also moving with the swipe. So, you should stick the `back button`, Title which is `Rule` and for progress, indicator takes a look here - [LINK](https://github.com/tommybuonomo/dotsindicator). what you've implemented its kind of a hacky way.
> 
> The rest looks good. :)

@hellosagar 
Hi, thank you for comment.
I will investigate your Link 🙇 and refactor my lib again.
I will check `back button`.

**Comment by ntvkhoasgt** [comment]
@hellosagar 
I fixed as your recommend. Please review

**Review by hellosagar — APPROVED** [review]
You've done a great job @ntvkhoasgt 

Thanks :)

**Pull request merged**
